services:
  - type: web
    name: car-plate-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y $(cat Aptfile)
      pip install -r requirements.txt
    startCommand: gunicorn app:app
