services:
  - type: web
    name: updated-car-adavanced-tesseract-ocr
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y $(cat Aptfile) && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
